# Generated by Django 4.1 on 2023-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='types',
            field=models.CharField(choices=[('OQ', 'Optional Question'), ('YN', 'Yes/No Question')], default='YN', max_length=2),
        ),
    ]
